#!/usr/bin/env node

var requirejs = require('requirejs')
requirejs.config({
    paths: {
        "deje": "../deje"
    },
    nodeRequire: require
})

requirejs(['deje/event','deje/document'], function(Event, Document) {
    var object_type = process.argv[2],
        format = process.argv[3],
        input = '';

    var object_types = {
        'event': function(input_object) {
            return new Event(input_object);
        },
        'document': function(input_object) {
            return new Document(input_object);
        },
    };
    var formats = {
        "hash": "",
        "compact": "",
        "pretty4": "    ",
    };

    process.stdin.on('data', function (chunk) {
        input += chunk;
    });
    process.stdin.on('end', function() {
        input_object = JSON.parse(input);
        built_object = object_types[object_type](input_object);
        output = built_object.serialize(formats[format]);
        //console.log(built_object);
        process.stdout.write(output);
    });
});
